-n 

2025-08-01-16.23.57.602426+540 I5E382               LEVEL: Error
PID     : 97023                TID : 8433884928     PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: changin
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:42
MESSAGE : DIA3222E The host name "YOUR_HOST" was not found, TCP/IP function 
          "getaddrinfo" error return code = "8".

2025-08-01-16.23.57.604524+540 I388E3628            LEVEL: Severe
PID     : 97023                TID : 8433884928     PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: changin
FUNCTION: DB2 UDB, DRDA Communication Manager, sqljcCommConnect, probe:10
MESSAGE : ZRC=0x81360012=-2127167470=SQLZ_RC_CMERR, SQLT_SQLJC
          "External Comm error"
DATA #1 : String, 11 bytes
CCI Error: 
DATA #2 : unsigned integer, 8 bytes
97
CALLSTCK: (Static functions may not be resolved correctly, as they are resolved to the nearest symbol)
  [0] 0x0000000104ED2F44 _Z16sqljcLogCCIErrorP10sqljCmnMgrPKcP12SQLCC_COND_Thllll + 0x1A8
  [1] 0x0000000104ED3A8C _Z16sqljcCommConnectP10sqljCmnMgr + 0x354
  [2] 0x0000000104ED3054 _Z15sqljcCmnMgrInitP10sqljCmnMgrP17SQLCC_COMHANDLE_TPhmP14db2UCconHandleh24sqljcInvokeCommExitStatePP21sqljcCommexitCommInfoP8s + 0xB4
  [3] 0x000000010513EBB8 _Z20sqljrCreateTransportP14db2UCconHandle + 0x144
  [4] 0x0000000104AAD870 _Z23sqljrAssociateTransportP14db2UCconHandlePlbP19SQLE_SRVLST_DBENTRYPi + 0x90
  [5] 0x000000010513E2F4 _Z26sqljrConnectBasedOnCatalogP14db2UCconHandlePibPb + 0x2A0
  [6] 0x000000010513D09C _Z20sqljrInternalConnectP14db2UCconHandlePbPib + 0x48C
  [7] 0x000000010513E9E8 _Z30sqljrFindBestAddressAndConnectP14db2UCconHandle + 0x70
  [8] 0x000000010511A3F4 _Z23sqljrDrdaArAuthenticateP14db2UCinterfacelPj + 0x1EC
  [9] 0x00000001050D3384 _Z20sqlexAppAuthenticateP14db2UCinterface + 0xA10
  [10] 0x000000010513ED04 _Z18sqljrDrdaArConnectP14db2UCinterface + 0xC0
  [11] 0x00000001050E6040 _Z16sqleUCdrdaARinitP14db2UCconHandle + 0xE8
  [12] 0x00000001052574FC sqleUCappConnect + 0xA8C
  [13] 0x0000000104AC4C28 _Z14CLI_sqlConnectP15CLI_CONNECTINFOP5sqlcaP19CLI_ERRORHEADERINFO + 0x1CA4
  [14] 0x0000000104B3FB90 _Z11SQLConnect2P15CLI_CONNECTINFOPhsS1_sS1_sS1_sh + 0x1320
  [15] 0x0000000104B3C774 _Z17SQLDriverConnect2P15CLI_CONNECTINFOPvPhsS2_sPsthhP19CLI_ERRORHEADERINFO + 0xBFD4
  [16] 0x0000000104BF609C SQLDriverConnectW + 0x8AC
  [17] 0x0000000103133464 _python_ibm_db_connect_helper + 0x10E4
  [18] 0x0000000102BFC3C8 cfunction_call + 0x54
  [19] 0x0000000102BB5E10 _PyObject_MakeTpCall + 0x164
  [20] 0x0000000102C88D8C call_function + 0x234
  [21] 0x0000000102C838C0 _PyEval_EvalFrameDefault + 0x1C78
  [22] 0x0000000102C81B44 _PyEval_Vector + 0x8C
  [23] 0x0000000102C88D30 call_function + 0x1D8
  [24] 0x0000000102C83898 _PyEval_EvalFrameDefault + 0x1C50
  [25] 0x0000000102C81B44 _PyEval_Vector + 0x8C
  [26] 0x0000000102C88D30 call_function + 0x1D8
  [27] 0x0000000102C83898 _PyEval_EvalFrameDefault + 0x1C50
  [28] 0x0000000102C81B44 _PyEval_Vector + 0x8C
  [29] 0x0000000102C88D30 call_function + 0x1D8
  [30] 0x0000000102C83898 _PyEval_EvalFrameDefault + 0x1C50
  [31] 0x0000000102C81B44 _PyEval_Vector + 0x8C
  [32] 0x0000000102C88D30 call_function + 0x1D8
  [33] 0x0000000102C83898 _PyEval_EvalFrameDefault + 0x1C50
  [34] 0x0000000102C81B44 _PyEval_Vector + 0x8C
  [35] 0x0000000102C88D30 call_function + 0x1D8
  [36] 0x0000000102C85768 _PyEval_EvalFrameDefault + 0x3B20
  [37] 0x0000000102C81B44 _PyEval_Vector + 0x8C
  [38] 0x0000000102C88D30 call_function + 0x1D8
  [39] 0x0000000102C85768 _PyEval_EvalFrameDefault + 0x3B20
  [40] 0x0000000102C81B44 _PyEval_Vector + 0x8C
  [41] 0x0000000102C81AA4 PyEval_EvalCode + 0x6C
  [42] 0x0000000102CC9100 run_mod + 0x98
  [43] 0x0000000102CC7918 _PyRun_SimpleFileObject + 0x34C
  [44] 0x0000000102CC73C4 _PyRun_AnyFileObject + 0xA0
  [45] 0x0000000102CE5760 Py_RunMain + 0x648
  [46] 0x0000000102CE5B10 pymain_main + 0x144
  [47] 0x0000000102CE5BB0 Py_BytesMain + 0x28
  [48] 0x000000018867EB98 start + 0x17BC

2025-08-01-16.26.39.437761+540 I4017E382            LEVEL: Error
PID     : 98068                TID : 6189789184     PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: changin
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:42
MESSAGE : DIA3222E The host name "YOUR_HOST" was not found, TCP/IP function 
          "getaddrinfo" error return code = "8".

2025-08-01-16.26.39.438454+540 I4400E3732           LEVEL: Severe
PID     : 98068                TID : 6189789184     PROC : python
INSTANCE: DB2                  NODE : 000
HOSTNAME: changin
FUNCTION: DB2 UDB, DRDA Communication Manager, sqljcCommConnect, probe:10
MESSAGE : ZRC=0x81360012=-2127167470=SQLZ_RC_CMERR, SQLT_SQLJC
          "External Comm error"
DATA #1 : String, 11 bytes
CCI Error: 
DATA #2 : unsigned integer, 8 bytes
97
CALLSTCK: (Static functions may not be resolved correctly, as they are resolved to the nearest symbol)
  [0] 0x0000000104C62F44 _Z16sqljcLogCCIErrorP10sqljCmnMgrPKcP12SQLCC_COND_Thllll + 0x1A8
  [1] 0x0000000104C63A8C _Z16sqljcCommConnectP10sqljCmnMgr + 0x354
  [2] 0x0000000104C63054 _Z15sqljcCmnMgrInitP10sqljCmnMgrP17SQLCC_COMHANDLE_TPhmP14db2UCconHandleh24sqljcInvokeCommExitStatePP21sqljcCommexitCommInfoP8s + 0xB4
  [3] 0x0000000104ECEBB8 _Z20sqljrCreateTransportP14db2UCconHandle + 0x144
  [4] 0x000000010483D870 _Z23sqljrAssociateTransportP14db2UCconHandlePlbP19SQLE_SRVLST_DBENTRYPi + 0x90
  [5] 0x0000000104ECE2F4 _Z26sqljrConnectBasedOnCatalogP14db2UCconHandlePibPb + 0x2A0
  [6] 0x0000000104ECD09C _Z20sqljrInternalConnectP14db2UCconHandlePbPib + 0x48C
  [7] 0x0000000104ECE9E8 _Z30sqljrFindBestAddressAndConnectP14db2UCconHandle + 0x70
  [8] 0x0000000104EAA3F4 _Z23sqljrDrdaArAuthenticateP14db2UCinterfacelPj + 0x1EC
  [9] 0x0000000104E63384 _Z20sqlexAppAuthenticateP14db2UCinterface + 0xA10
  [10] 0x0000000104ECED04 _Z18sqljrDrdaArConnectP14db2UCinterface + 0xC0
  [11] 0x0000000104E76040 _Z16sqleUCdrdaARinitP14db2UCconHandle + 0xE8
  [12] 0x0000000104FE74FC sqleUCappConnect + 0xA8C
  [13] 0x0000000104854C28 _Z14CLI_sqlConnectP15CLI_CONNECTINFOP5sqlcaP19CLI_ERRORHEADERINFO + 0x1CA4
  [14] 0x00000001048CFB90 _Z11SQLConnect2P15CLI_CONNECTINFOPhsS1_sS1_sS1_sh + 0x1320
  [15] 0x00000001048CC774 _Z17SQLDriverConnect2P15CLI_CONNECTINFOPvPhsS2_sPsthhP19CLI_ERRORHEADERINFO + 0xBFD4
  [16] 0x000000010498609C SQLDriverConnectW + 0x8AC
  [17] 0x0000000102A3B464 _python_ibm_db_connect_helper + 0x10E4
  [18] 0x00000001014843C8 cfunction_call + 0x54
  [19] 0x000000010143DE10 _PyObject_MakeTpCall + 0x164
  [20] 0x0000000101510D8C call_function + 0x234
  [21] 0x000000010150B8C0 _PyEval_EvalFrameDefault + 0x1C78
  [22] 0x0000000101509B44 _PyEval_Vector + 0x8C
  [23] 0x0000000101510D30 call_function + 0x1D8
  [24] 0x000000010150B898 _PyEval_EvalFrameDefault + 0x1C50
  [25] 0x0000000101509B44 _PyEval_Vector + 0x8C
  [26] 0x0000000101510D30 call_function + 0x1D8
  [27] 0x000000010150B898 _PyEval_EvalFrameDefault + 0x1C50
  [28] 0x0000000101509B44 _PyEval_Vector + 0x8C
  [29] 0x0000000101510D30 call_function + 0x1D8
  [30] 0x000000010150B898 _PyEval_EvalFrameDefault + 0x1C50
  [31] 0x0000000101509B44 _PyEval_Vector + 0x8C
  [32] 0x0000000101510D30 call_function + 0x1D8
  [33] 0x000000010150B898 _PyEval_EvalFrameDefault + 0x1C50
  [34] 0x0000000101509B44 _PyEval_Vector + 0x8C
  [35] 0x000000010150BF40 _PyEval_EvalFrameDefault + 0x22F8
  [36] 0x0000000101509B44 _PyEval_Vector + 0x8C
  [37] 0x0000000101510D30 call_function + 0x1D8
  [38] 0x000000010150B898 _PyEval_EvalFrameDefault + 0x1C50
  [39] 0x0000000101509B44 _PyEval_Vector + 0x8C
  [40] 0x0000000101510D30 call_function + 0x1D8
  [41] 0x000000010150B898 _PyEval_EvalFrameDefault + 0x1C50
  [42] 0x0000000101509B44 _PyEval_Vector + 0x8C
  [43] 0x0000000101510D30 call_function + 0x1D8
  [44] 0x000000010150B898 _PyEval_EvalFrameDefault + 0x1C50
  [45] 0x0000000101509B44 _PyEval_Vector + 0x8C
  [46] 0x000000010143DC3C _PyObject_FastCallDictTstate + 0x10C
  [47] 0x000000010143E754 _PyObject_Call_Prepend + 0x98
  [48] 0x00000001014A5A54 slot_tp_call + 0x68
  [49] 0x000000010143DE10 _PyObject_MakeTpCall + 0x164
